import { StyleSheet } from "react-native";
import { authColors } from "../constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1 },
  containerRow: { flexDirection: "row" },
  panelFlex: { flex: 1 },
  formPanel: {
    flex: 1,
    backgroundColor: authColors.formBackground,
    justifyContent: "center",
    paddingHorizontal: 24,
    paddingVertical: 40,
  },
  formInner: { width: "100%", maxWidth: 340, alignSelf: "center" },
  title: {
    color: authColors.text,
    fontSize: 26,
    fontWeight: "700",
    marginBottom: 24,
  },
  input: {
    borderWidth: 1,
    borderColor: authColors.border,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    color: authColors.text,
    marginBottom: 14,
  },
  passwordWrapper: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    borderWidth: 1,
    borderColor: authColors.border,
    borderRadius: 8,
    paddingHorizontal: 14,
    paddingVertical: 12,
    marginBottom: 14,
  },
  passwordInput: { flex: 1, color: authColors.text },
  rowBetween: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  checkboxRow: { flexDirection: "row", alignItems: "center" },
  checkbox: {
    width: 16,
    height: 16,
    borderWidth: 1,
    borderColor: authColors.checkboxBorder,
    borderRadius: 3,
    marginRight: 8,
  },
  checkboxChecked: { backgroundColor: authColors.checkboxChecked },
  smallText: { color: authColors.textMuted, fontSize: 13 },
  link: { color: authColors.link, fontSize: 13, fontWeight: "600" },
  primaryButton: {
    backgroundColor: authColors.primary,
    borderRadius: 8,
    paddingVertical: 14,
    alignItems: "center",
    marginBottom: 12,
  },
  primaryButtonText: { color: authColors.primaryText, fontWeight: "700" },
  footerRow: { flexDirection: "row", justifyContent: "center" },
  illustrationPanel: {
    backgroundColor: authColors.illustrationBackground,
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 60,
  },
  illustrationTitle: {
    fontSize: 48,
    fontWeight: "700",
    color: authColors.illustrationText,
    marginBottom: 0,
  },
  iconBadge: {
    width: 200,
    height: 200,
    borderRadius: 16,
    // backgroundColor: authColors.badgeBackground,
    alignItems: "center",
    justifyContent: "center",
  },
  logoImage: {
    width: "100%",
    height: "100%",
    marginTop: 14,
  },
  errorContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginTop: 4,
    marginBottom: 12,
  },
  errorText: {
    color: "#e0533d",
    fontSize: 13,
    fontWeight: "500",
  },
});
